version: '3.1'

services:
  bicycledb:
    container_name: bicycledb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: bicycles
    ports:
    - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/data